# Generated by Django 3.1.4 on 2021-03-25 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_profile_is_hidden'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='follows',
            name='profile',
        ),
        migrations.DeleteModel(
            name='Following',
        ),
        migrations.DeleteModel(
            name='Follows',
        ),
    ]
