# Generated by Django 3.1.4 on 2021-03-25 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210325_1503'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('M', 'Erkek'), ('F', 'Kadın'), ('U', 'Bilinmiyor')], default='U', max_length=1),
        ),
        migrations.AddField(
            model_name='profile',
            name='name',
            field=models.CharField(default='Username', max_length=75),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='phone',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='webpage',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
