# Generated by Django 3.1.7 on 2021-02-28 22:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='follow',
            name='followed',
        ),
        migrations.RemoveField(
            model_name='follow',
            name='follower',
        ),
        migrations.AddField(
            model_name='follow',
            name='followeds_list',
            field=models.ManyToManyField(related_name='followeds', to='api.Profile'),
        ),
        migrations.AddField(
            model_name='follow',
            name='followers_list',
            field=models.ManyToManyField(related_name='followers', to='api.Profile'),
        ),
        migrations.AddField(
            model_name='follow',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.profile'),
            preserve_default=False,
        ),
    ]
