# Generated by Django 3.1.4 on 2021-03-25 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20210325_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='followers',
            name='follower',
            field=models.ManyToManyField(blank=True, null=True, related_name='follower', to='api.Profile'),
        ),
    ]
