# Generated by Django 3.1.7 on 2021-02-28 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20210301_0141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='follow',
            name='followeds_list',
            field=models.ManyToManyField(blank=True, null=True, related_name='followeds', to='api.Profile'),
        ),
        migrations.AlterField(
            model_name='follow',
            name='followers_list',
            field=models.ManyToManyField(blank=True, null=True, related_name='followers', to='api.Profile'),
        ),
    ]
