# Generated by Django 3.1.4 on 2021-03-26 20:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20210326_2335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='followers',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.profile'),
        ),
    ]
